### ISSUE TITLE
Support for Google Drive as File source

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#1044]
Create support for google drive as a file location. A file(s) kept in google drive would be now loaded into the databases and can perform operations on it. 
For this, we use the Google API client to connect and retrieve the file.

One endpoint is used:

* [`files().list()`](https://developers.google.com/drive/api/v3/reference/files/list) to find files.

To use those file APIs you need to kind of visualise traversing the folders in a GUI. To get a file by path, you need to see what items are available in a folder and select the one with the name you want. If the item is a folder, you need to run the list against it again to see what items are in it. Not very efficient, but there are not many choices.

**Comment by uranusjr** [comment]
A few thoughts from initial observations and investigations:

1. Airflow’s GoogleDriveHook is pretty lacking at the moment[^1]. So we either need to contribute to that first, or just roll our own implementation in the SDK.
2. There’s a new Python package called [fsspec](https://filesystem-spec.readthedocs.io/) that provides file API for Google Drive (and some other storages). It is gaining populatiry recently.
3. We are currently using `smart_open`, which lacks Google Drive support. So we need to implement a [custom transport](https://github.com/RaRe-Technologies/smart_open/blob/master/extending.md) for it.
4. But fsspec actully can also do `open`, so it’s entirely possible to replace `smart_open` with fsspec for our purposes. And since fsspec has built-in Google Drive support, we’ll be able to add it more easily.

I’m wondering how it’s best to approach this. We can either replace `smart_open` with fsspec, or implement a custom `smart_open` transport. If we decide to go with the latter, we can also try to implement the custom transport directly with Google API client, or add fsspec as a dependency.

[^1]: Currently only methods to check, read, and write a file.

**Comment by uranusjr** [comment]
I took a look at fsspec’s Google Drive implementation and it seems easy enough to just use the API client, so I’m going to do that for now.

I wonder if there’s a good way to test the classes. A Moto equivalent for googleapiclient would be useful…

**Comment by uranusjr** [comment]
PR to add the file location has been created (see ref link above)
