### ISSUE TITLE
CI: `example_load_file.py` isnt running

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astro-sdk#1163]
**Describe the bug**
 The `python-sdk/example_dags/example_load_file.py` example DAG in not running in our CI tests

**Version**
* Astro: [e.g. 0.6.0]
* OS: [eg. Debian]

**To Reproduce**
1. Write the DAG  '...'
2. Create connection '....'
3. Run using  '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pankajastro** [comment]
Since the file does not exist load_file_to_table_natively is failing and it falls for the pandas path. In the pandas path the resolve_file_path_pattern converting path pattern to gs://astro-sdk/workspace/sample_pattern.csv and luckly we do have this file in GCS. 

Why extractor tests is failing? since I'm my PR we have changed the enable native fallback behaviour
