### ISSUE TITLE
Be able to run SQL CLI workflows on Airflow / Astro CLI locally

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1315]
**Please describe the feature you'd like to see**
As of SQL CLI 0.2, all the workflows rely on SQLite. We mount those during `astro flow` commands but are not mounted during `astro dev start`. This means users cannot have an end-to-end journey using the SQL CLI / Astro CLI, where they'd visualise the workflow they built with SQL.

**Describe the solution you'd like**
It would be great to find a strategy so users can visualise/run example DAGs in Astro CLI - until we define the documentation journey.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by feluelle** [comment]
What astro-cli already has:
* `$AIRFLOW_HOME/include` directory for mounting additional directories/files

What flow depends on:
* data directory for local file (sqlite) dbs

One option could be to copy the flow projects into the include directory:

This could be done using something like:
```
astro dev start --include path/to/flow_project_1,another_path/to/flow_project_2
```
which would copy to astro's `$AIRFLOW_HOME/include` (natively). We create a new feature for copying on demand directories/files.

OR by using something like:
```
cp path/to/flow_project_1/data ./include/flow_project_1_data
cp path/to/flow_project_2/data ./include/flow_project_2_data
```
executed in the astro-cli project directory (non-natively). Note we only need `data` directory here, because we can be explicit as we control where the files/directories lands.

Then we create connections in airflow (as a starting point manually) and set the host path accordingly i.e. to where we have moved the files to.

**Comment by pankajkoti** [comment]
Another option suggested by Tatiana:
We accept another parameter during projection initialisation that the user can specify as their example data directory.

**Comment by tatiana** [comment]
TODO: update the docs once we can run the workflows within Astro CLI:
https://github.com/astronomer/docs/blob/main/astro/cli/sql-cli.md

**Comment by feluelle** [comment]
Re-opening as docs are missing and need to verify once more that it works now.
