### ISSUE TITLE
Change benchmark reporting to expose the information from GCS to Markdown

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#442]
**Dependencies**
* Depends on: #432
* Depends on: #434

**Acceptance criteria**
* [ ] Change the script which consolidates the output of our benchmarks to retrieve the values stored in GCS and generate markdown tables

**References**
* Script which converts results into markdown: https://github.com/astronomer/astro-sdk/blob/main/tests/benchmark/analyse.py

**Comment by sunank200** [comment]
Currently [run.sh](https://github.com/astronomer/astro-sdk/blob/main/tests/benchmark/run.sh) produces results as `ndjson` files and then, [analyze](https://github.com/astronomer/astro-sdk/blob/main/tests/benchmark/analyse.py) runs and produces markdown. [run.sh](https://github.com/astronomer/astro-sdk/blob/main/tests/benchmark/run.sh) also copies the results to GCS.

So instead of querying GCS, [run.sh](https://github.com/astronomer/astro-sdk/blob/main/tests/benchmark/run.sh) can call [analyze](https://github.com/astronomer/astro-sdk/blob/main/tests/benchmark/analyse.py) which produces markdown.
