### ISSUE TITLE
Docs: add "Operators" to "Reference" and to have "Concepts" include some more high level documentation

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#694]
Looks a lot cleaner! I don't feel strongly either way, but in the future it might make sense to add "Operators" to "Reference" and to have "Concepts" include some more high level documentation. Knowing what each operator does _seems_ more referency to me. 

But because "Concepts" is only one doc for now, I think this structure works for the content we have.

_Originally posted by @jwitz in https://github.com/astronomer/astro-sdk/pull/692#pullrequestreview-1077794972_

**Comment by pankajastro** [comment]
The current operator section https://astro-sdk-python.readthedocs.io/en/stable/guides/operators.html have some high-level concept about the operator-like use case and I feel the concept is the right place/section for this. I'm not sure if we need any changes for this.

**Comment by pankajastro** [comment]
@jwitz can you please add some more details here like what needs to be done for this ticket? thank you.

**Comment by jwitz** [comment]
@pankajastro We can close this issue because my thoughts have evolved a bit since I wrote that message. Overall, I think the SDK guides should focus on "How to" guides for common actions/ pipeline structures, rather than for the operators themselves. So example, instead of a guide called `drop table operator`, we have a guide called "Drop a table".
