### ISSUE TITLE
Add Benchmarking data for REDSHIFT

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astro-sdk#748]
**Please describe the feature you'd like to see**
Right now we don't benchmark data for the redshift database.

**Describe the solution you'd like**
We need to run benchmarking script on the redshift database.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))

**Comment by pankajkoti** [comment]
The benchmarking script is failing due to multiple failures. I see it has mostly failed in the last few days on the Kubernetes cluster. 
I tried making changes to the script, was able to make a few fixes related to path caused after the folder restructuring.
The image is getting built well now locally. Upon running locally, it starts but gets killed after a while. Also, it fails to launch on Kubernetes cluster. Will seek help from @utkarsharma2 & @tatiana

**Comment by pankajkoti** [comment]
Will pair up with @sunank200 post stand up call to resolve this.
