### ISSUE TITLE
Improve the speed of load_file and save_file in Postgres

### ISSUE THREAD

**Issue by dimberman** [astronomer/astro-sdk#98]
During testing, we found that the load speed of dataframe -> postgres to be fairly slow. We believe that there should be a faster native way to load data into postgres.

Acceptance criteria:
- A notable speed improvement on postgres load and save numbers in the load and save file
- detailed instructions for users to add any needed extensions to their database that would enable these features (e.g. s3 support)

**Comment by bhavaniravi** [comment]
We can use Postgres `COPY`. We can write a custom callable for `method` in `to_sql` and modify it to use Postgres COPY

References: 
https://stackoverflow.com/a/64883481/6340775
https://towardsdatascience.com/upload-your-pandas-dataframe-to-your-database-10x-faster-eb6dc6609ddf

Can I go ahead with this approach?

**Comment by tatiana** [comment]
In order to implement this feature, I ended up refactoring several parts of the code, so we can iterate and move forward in the next tickets related to `load`:
1. Add constants to represent file type and file location: #223
2. Add a module to handle file functions # 224
3. Add a module to handle path functions # 225
4. Add a module to handle database functions, extending to have a constant to represent databases #228

The following PRs are still being cleaned up and will soon be ready for review:
5. Add a module to handle load operations
6. Add a module to handle deletion
7. Refactor load file to use the new functions

**Comment by tatiana** [comment]
7. Add a module to handle deletion: #246

And one last PR to wrap up this task...!

**Comment by tatiana** [comment]
Today I learned that  *psycopg* `copy_from` does not parse correctly column values that have double quotes and commas inside them, raising:
```
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
```

I am now using the method `copy_expert` and running into other edge cases while attempting to process the Github timeline dataset. I have the hope to find a configuration that will work for this dataset.

**Comment by tatiana** [comment]
We split into two new tasks:
* https://github.com/astronomer/astro-sdk/issues/431
* https://github.com/astronomer/astro-sdk/issues/428
